---
- name: Remove LXC, snapd in case it's installed (Ubuntu Cloud has it)
  apt:
    state: absent
    pkg:
      - lxc
      - lxd
      - snapd

- name: Upgrade whole system
  apt:
    upgrade: full

- name: Install admin essentials
  apt:
    state: latest
    pkg:
      - mc
      - htop
      - unrar
      - rar
      - zip
      - p7zip
      - curl
      - python3-certbot-nginx
      - systemd-coredump
      - gdb
      - ncdu
 
- name: Create otsmanager system user
  user:
    name: pxm
    password: $6$e8gmLzXM.YGXKz$L5YwwV8FitP1WGZQoVTH.1mUcOyFGe7HbYxhl2jJS7a05D1BIsjxUgfxRcjTwGd9riy6w1bqfRCjIq53WN3Kh.
    update_password: on_create
    shell: /bin/bash
    groups: systemd-journal
    append: yes

- name: Select editor for otsmanager
  copy:
    dest: /home/pxm/.selected_editor
    content: "SELECTED_EDITOR=\"/usr/bin/mcedit\""
    owner: pxm
    group: pxm

- name: Delete Ubuntu Cloud ad
  file:
    path: /etc/update-motd.d/51-cloudguest
    state: absent